In [2]:
import numpy as np
x = [3,2,4,5,1]
y = np.array(x)
y

array([3, 2, 4, 5, 1])

### Mengurutkan Array

In [7]:
np.sort(y)

array([1, 2, 3, 4, 5])

In [38]:
# Mengurutkan tanpa menggunakan function sort
k = [3,2,4,6,5,1]
a = []
a.append(k[0])
for i in k:
    if i > a[-1]:
        a.append(i)
    elif i < a[0]:
        a.insert(0, i)
a

[1, 2, 3, 4, 6]

In [58]:
# cara mengurutkan dari mas Lintang
x = [71,6,1,54,2,2,93,73]
sortir = []
minX = x[0]
while len(x) > 0:
    if x[i] < minX:
        minX = x[i]
    i += 1
    if i == len(x):
        sortir.append(minX)
        x.remove(minX)
        if x:
            minX = x[0]
        i = 0
sortir

[1, 2, 2, 6, 54, 71, 73, 93]

### Membalikkan Urutan

In [6]:
x.sort(reverse=True)
x

[5, 4, 3, 2, 1]

In [8]:
np.sort(y)[::-1]

array([5, 4, 3, 2, 1])

### Mengurutkan Numpy Array

#### Mengurutkan by column

In [65]:
z = [[9,10,2],
     [5,1,4]]
z = np.array(z)
np.sort(z, axis=0) #mengurutkan by column

array([[ 5,  1,  2],
       [ 9, 10,  4]])

#### Mengurutkan by row

In [64]:
z = [[9,10,2],
     [5,1,4]]
z = np.array(z)
np.sort(z, axis=1) #mengurutkan by row

array([[ 2,  9, 10],
       [ 1,  4,  5]])

In [66]:
np.sort(z, axis=None) #mengurutkan dan menjadi satu baris

array([ 1,  2,  4,  5,  9, 10])

### Swap

In [5]:
x = np.arange(1,10).reshape(3, -1)

x[:, [1, 0, 2]] #urutan index

array([[2, 1, 3],
       [5, 4, 6],
       [8, 7, 9]])

In [72]:
x[:, [0, 0, 0]]

array([[1, 1, 1],
       [4, 4, 4],
       [7, 7, 7]])

In [74]:
x[[1,0,2], :]

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

### Transpose Numpy

a b
c d  => a c e
e f     b d f

1 2
3 4 => 1 3 5
5 6    2 4 6

In [6]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print(a.transpose())

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]
